# Generated by Django 3.1.7 on 2021-05-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='landmark',
        ),
    ]
