# Generated by Django 3.1.7 on 2021-05-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210510_2139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Provider',
        ),
    ]
