# Generated by Django 3.1.7 on 2021-05-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210512_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='resource',
            new_name='name',
        ),
    ]
