# Generated by Django 3.1.7 on 2021-05-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_resource_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
