# Generated by Django 3.1.7 on 2021-05-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
