# Generated by Django 3.1.7 on 2021-05-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_contact_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='state',
        ),
    ]
