# Generated by Django 3.1.7 on 2021-05-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_remove_provider_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
