# Generated by Django 3.1.7 on 2021-05-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_provider_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.state'),
        ),
    ]
