# Generated by Django 3.1.7 on 2021-05-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_resource_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='state',
        ),
    ]
