# Generated by Django 3.1.7 on 2021-05-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_remove_resource_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='avail',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
